//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int ID { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime submitted { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> requestType_id { get; set; }
        public Nullable<int> userAccount_id { get; set; }
    
        public virtual department department { get; set; }
        public virtual requestType requestType { get; set; }
        public virtual userAccount userAccount { get; set; }
    }
}
